
osx_image: xcode6.4
language: objective-c

before_install:
    - gem install cocoapods --pre --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - cd Demo
    - pod update
    - xctool -workspace Demo.xcworkspace -scheme 'Demo' -configuration Release -sdk iphonesimulator -arch i386 build
    - cd ..
    - mv Demo/Pods/Target\ Support\ Files/Pods/Pods-acknowledgements.plist .
    - pod lib lint
